#!/usr/bin/python3

from sys import argv
from math import sqrt


def factors(n):
    if n % 2 == 0:
        return n, n // 2, 2
    for q in range(3, int(sqrt(n)) + 1, 2):
        if n % q == 0:
            return n, n // q, q
    return n, n, 1


if len(argv) != 2:
    print("Usage: factors <file>")

with open(argv[1], mode="r") as f:
    for line in f:
        n = int(line)
        f = factors(n)
        print("{}={}*{}".format(f[0], f[1], f[2]))
