#!/usr/bin/python3
""" Gets two first factors of any number """
from sys import argv, stderr
import math

if len(argv) != 2:
    stderr.write("Usage: factors <file>\n")
    exit(1)

with open(argv[1], 'r') as f:
    for line in f:
        num = int(line)
        if num % 2 == 0:
            i = 2
            print("{:d}={:d}*{:d}".format(num, int(num/i), i))
        else:
            fa = int(math.sqrt(num)) + 1
            for i in range(3, fa, +2):
                if num % i == 0:
                    print("{:d}={:d}*{:d}".format(num,
                                                  int(num/i), i))
                    break
                if num % (fa + i) == 0:
                    print("{:d}={:d}*{:d}".format(num,
                                                  fa + i,
                                                  int(num/(fa + i))))
                    break
                if num % (fa - i) == 0:
                    print("{:d}={:d}*{:d}".format(num,
                                                  fa - 1,
                                                  int(num/(fa - i))))
                    break
